#!/bin/bash

if [ -x /usr/bin/lsb_release ]; then
  dist_name=$(lsb_release -is)
  if [ "$dist_name" = "Ubuntu" ]; then
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    sudo apt-get update
    sudo apt-get install sublime-text
  else
    echo "This command can't work on $dist_name"
  fi
else
  echo "Unknown linux version"
fi
